#!/usr/bin/env python3

import subprocess
import sys
import re

while True:
    useless_cat_call = subprocess.Popen(["/home/dhruva/winhome/AppData/Local/Android/Sdk/platform-tools/adb.exe", "shell"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    output, _ = useless_cat_call.communicate(input="dumpsys notification --noredact")
    useless_cat_call.wait()

    match_iter = re.finditer(r"NotificationRecord.*?pkg=(.*?)\ u.*?text=.*?\((.*?)\)", output, flags=re.DOTALL)

    matches = [match for match in match_iter]

    for i in range(len(matches)):
        match = matches[i]
        print(i,"] ", ".".join(match.groups()[0].split(".")[-2:]), ": ", match.groups()[1].replace("\n", " "))

    inp = input("[NUM/r/q]: ")
    if inp.isdigit():
        idx = int(inp)
        pkg = matches[idx].groups()[0]
        useless_cat_call = subprocess.Popen(["/home/dhruva/winhome/AppData/Local/Android/Sdk/platform-tools/adb.exe", "shell"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        output, err = useless_cat_call.communicate(input="monkey -p " + pkg + " 1")
        useless_cat_call.wait()
        print(output)
        print(err)
    elif inp=="q":
        break
    else:
        pass
