#!/usr/bin/env python3

import adb_config
import sys
import subprocess
import os

def _preprocess(text):
    return text.translate(str.maketrans({"`": r"\`"}))

def text(adbpath, text):
    subprocess.run([adbpath, "shell", "input","keyboard", "text", "\""+_preprocess(text)+"\n\""])

if __name__ == "__main__":
    adbpath = adb_config.getpath()
    if len(sys.argv) > 1:
        text(adbpath, " ".join(sys.argv[1:]))
    else:
        while True:
            _in = input("[In]: ")
            text(adbpath, _in)
